/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'id' : SubmissionId,
  'name' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'serviceInterest' : ServiceInterest,
  'message' : string,
  'phone' : string,
}
export type ServiceInterest = { 'Both' : null } |
  { 'BusinessSolutions' : null } |
  { 'Photography' : null };
export type SubmissionId = bigint;
export interface SubmitContactForm {
  'name' : string,
  'email' : string,
  'serviceInterest' : string,
  'message' : string,
  'phone' : string,
}
export type SubmitResult = { 'ok' : SubmissionId } |
  { 'err' : string };
export type Timestamp = bigint;
export interface _SERVICE {
  'listContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'submitContactForm' : ActorMethod<[SubmitContactForm], SubmitResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];