/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubmissionId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ServiceInterest = IDL.Variant({
  'Both' : IDL.Null,
  'BusinessSolutions' : IDL.Null,
  'Photography' : IDL.Null,
});
export const ContactSubmission = IDL.Record({
  'id' : SubmissionId,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'serviceInterest' : ServiceInterest,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const SubmitContactForm = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'serviceInterest' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const SubmitResult = IDL.Variant({
  'ok' : SubmissionId,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'listContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func([SubmitContactForm], [SubmitResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubmissionId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ServiceInterest = IDL.Variant({
    'Both' : IDL.Null,
    'BusinessSolutions' : IDL.Null,
    'Photography' : IDL.Null,
  });
  const ContactSubmission = IDL.Record({
    'id' : SubmissionId,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'serviceInterest' : ServiceInterest,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SubmitContactForm = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'serviceInterest' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SubmitResult = IDL.Variant({ 'ok' : SubmissionId, 'err' : IDL.Text });
  
  return IDL.Service({
    'listContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func([SubmitContactForm], [SubmitResult], []),
  });
};

export const init = ({ IDL }) => { return []; };